apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  version: 8.17.0
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: orenes
    count: 1
    config:
      node.store.allow_mmap: false
